#ifndef LRC_DEVCOMMON
#define LRC_DEVCOMMON
//#include <tinyxml2.h>
#include <iostream>
#include <cstring>
#include <map>
#include <memory>
#include <string>
#include <unordered_map>
#include <vector>
#include <random>
#include <algorithm>
#include <set>
#include <functional>
//#include <mutex>
//#include <libmemcached/memcached.h>
#include <chrono>
#include <time.h>
#include <fstream>
#include "jerasure.h"
#include "reed_sol.h"
#endif